### ISSUE TITLE
Window is cut-off on low res displays

### ISSUE THREAD

**Issue by Seeker14491** [imthe666st/NTRClient#25]
The bottom of the `ntrclient.exe` window is cut off on my laptop's 1366 by 768 pixel display. The buttons near the bottom are unclickable. I can't resize the window so it fits.

I'm running version 1.7-1 on Windows 10; here's what it looks like:

![ntr_cut_off](https://cloud.githubusercontent.com/assets/6490497/16970544/7068ed3a-4de2-11e6-8174-e74542e5abbd.png)

**Comment by imthe666st** [comment]
Hmm.. never thought somebody would use a display with a resolution of that size.  

I'll see what I can do.

**Comment by imthe666st** [comment]
Added / Fixed.  

You can now resize the window down. For now use this build attached. It has the version number as your current one and you will still receive update notices. 
[Nightly-e4b5077.zip](https://github.com/imthe666st/NTRClient/files/372981/Nightly-e4b5077.zip)
