### ISSUE TITLE
[Wiki] Gateshark page: DxData codes

### ISSUE THREAD

**Issue by Seeker14491** [imthe666st/NTRClient#26]
It appears the 0xD6, 0xD7, and 0xD8 codes are swapped with the 0xD9, 0xDA, and 0xDB codes respectively. I believe [this page](http://gamehacking.org/vb/threads/6328-NDS-Action-Replay-Code-Types), which is for the NDS Action Replay, shows the correct order. ("DxData" is called "stored" on that page). I looked at [this code](http://www.fort42.com/gateshark/game1908/9022/) which uses this "DxData" register, and the code didn't make sense with the current "DxData" explanations. 

Also, the addresses in these six instructions are offset by `offset`, which should be mentioned.

**Comment by imthe666st** [comment]
Swapped the gateshark codes in the wiki and in the code with commit 4fbb7d1

**Comment by Seeker14491** [comment]
It looks to me like the code was correct already; I was only pointing out a mistake on the wiki. The code should be reverted.

**Comment by imthe666st** [comment]
In the wiki it currently says that 0xD6-0xD8 are for reading and 0xD9-0xDB are for writing.  
In the code 0xD6-0xD8 also read and 0xD9-0xDB write.

**Comment by Seeker14491** [comment]
It's ambiguous what you mean by "read" and "write". All of these commands read something and write something. Here's a snip of `gateshark.cs`:
```
else if (cmd == 0xD6) // DxData read WORD
{
    uint addr = gsAr.getBlock_B() + _offset;
    _dxData = CmdWindow.FromLe(Program.GCmdWindow.readValue(addr, 4), 4);
}
```

The 0xD6-0xD8 commands shouldn't modify DxData. They read DxData and write to memory.

**Comment by imthe666st** [comment]
So.. 0xD6-0xD8 shall READ from the dxData and WRITE to memory? And the 0xD9-0xDB do the reverse?

**Comment by Seeker14491** [comment]
Yes.

**Comment by imthe666st** [comment]
Switched them again in the code.
