### ISSUE TITLE
toInt32 convert problem

### ISSUE THREAD

**Issue by vitortexc** [imthe666st/NTRClient#8]
Problem with this codes: http://www.fort42.com/gateshark/game1852/

Stack Trace :

************** Texto de Exceção **************
System.OverflowException: Value too big or too small for Int32.
   em System.Convert.ToInt32(UInt32 value)
   em ntrclient.gateshark.execute() na C:\Users\Philip\Documents\Visual Studio 2015\git\NTRClient\ntrclient\gateshark.cs:linha 139
   em ntrclient.CmdWindow.button_gateshark_execute_Click(Object sender, EventArgs e) na C:\Users\Philip\Documents\Visual Studio 2015\git\NTRClient\ntrclient\CmdWindow.cs:linha 568
   em System.Windows.Forms.Control.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ButtonBase.WndProc(Message& m)
   em System.Windows.Forms.Button.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblies Carregados **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1063.1 built by: NETFXREL3STAGE
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ntrclient
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Users/Tex/Desktop/ntrclient/ntr%20client%20improved/ntrclient.exe
----------------------------------------
IronPython
    Versão do Assembly: 2.7.5.0
    Versão do Win32: 2.7.5.1000
    Base de Código: file:///C:/Users/Tex/Desktop/ntrclient/ntr%20client%20improved/IronPython.DLL
----------------------------------------
Microsoft.Scripting
    Versão do Assembly: 1.1.0.20
    Versão do Win32: 1.1.0.21
    Base de Código: file:///C:/Users/Tex/Desktop/ntrclient/ntr%20client%20improved/Microsoft.Scripting.DLL
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1068.2 built by: NETFXREL3STAGE
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Dynamic
    Versão do Assembly: 1.1.0.20
    Versão do Win32: 1.1.0.21
    Base de Código: file:///C:/Users/Tex/Desktop/ntrclient/ntr%20client%20improved/Microsoft.Dynamic.DLL
----------------------------------------
System.Numerics
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
IronPython.Modules
    Versão do Assembly: 2.7.5.0
    Versão do Win32: 2.7.5.1000
    Base de Código: file:///C:/Users/Tex/Desktop/ntrclient/ntr%20client%20improved/IronPython.Modules.DLL
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1064.2 built by: NETFXREL3STAGE
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 4.6.1064.2 built by: NETFXREL3STAGE
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Versão do Win32: 4.6.1063.1 built by: NETFXREL3STAGE
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.6.1038.0 built by: NETFXREL2
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by imthe666st** [comment]
Which of these codes did you use? You only told me the game.

**Comment by imthe666st** [comment]
Tested on some dummy codes. If the error isn't fixed please open another issue.

**Comment by vitortexc** [comment]
Sorry for the missing of information.
The problem was with those that give maximaze something, the ones with "FFFFxxxx" as value to be inserted.
Tested the new version and the problem get fixed. Thanks.

**Comment by imthe666st** [comment]
No problem :)
